# Generated by Django 4.1.1 on 2022-10-05 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Name',
            field=models.CharField(default='Guest', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.ForeignKey(default='guest@guest.com', on_delete=django.db.models.deletion.CASCADE, to='doctorApp.users'),
        ),
    ]
