# Generated by Django 4.1.1 on 2022-10-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0002_appointment_name_appointment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='guest@guest.com', max_length=254),
        ),
    ]
