# Generated by Django 4.1.1 on 2022-10-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0003_alter_appointment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
