# Generated by Django 4.0.1 on 2022-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0004_alter_appointment_name_alter_appointment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Doctor',
            field=models.CharField(default='Dr. Joe', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Schedule',
            field=models.CharField(default='', max_length=200),
        ),
    ]
