# Generated by Django 4.0.1 on 2022-10-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0007_remove_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Doctor',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Schedule',
            field=models.CharField(default='', max_length=200),
        ),
    ]
