# Generated by Django 4.0.1 on 2022-10-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0008_appointment_doctor_appointment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Time',
        ),
    ]
