# Generated by Django 4.0.1 on 2022-10-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorApp', '0012_remove_appointment_time_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Disease',
            field=models.CharField(default='Cold', max_length=200),
        ),
    ]
